### ISSUE TITLE
Explain `function.json`

### ISSUE THREAD

**Issue by devgioele** [horihiro/azure-functions-sqlbinding-js-example#1]
According to the [json schema](http://json.schemastore.org/function), the [function.json for HttpTriggerInputBinding](https://github.com/horihiro/azure-functions-sqlbinding-js-example/blob/main/HttpTriggerInputBinding/function.json) is invalid. I cannot find an up-to-date documentation.

Could someone explain the keys `CommandType` and `CommandText`? Especially how `[dbo].[Employees]` is processed. Where does `dbo` come from?

The [C# guide](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-output?tabs=in-process&pivots=programming-language-csharp#attributes) says that `CommandText` is the name of the table being written to by the binding, but this repo uses it to pass the SQL query.

**Comment by horihiro** [comment]
> The [C# guide](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-output?tabs=in-process&pivots=programming-language-csharp#attributes) says that CommandText is the name of the table being written to by the binding, but this repo uses it to pass the SQL query.

You referred to the guide about **output** binding and the `function.json` is for **input** binding.

The guide for **input** binding says as below.
![image](https://user-images.githubusercontent.com/4566555/167317324-36b0f37c-3ebe-4e3e-9595-683f24184f96.png)  
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-input?tabs=in-process&pivots=programming-language-csharp#attributes

The function in this repo uses `Transact-SQL query command`.

I'm not sure when the SQL binding is described in the json schema.

**Comment by devgioele** [comment]
Thank you. I figured out that `dbo` comes from an Azure convention. Although it would be nice if they update the json schema
